// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/01/2025, 12:05:07
const configMerger = require("C:/repos/PeakNovelGo/frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {
  content: [],
  theme: {
    extend: {
      colors: {
        primary: "#1a202c", // equivalent to bg-gray-900
        secondary: "#2d3748", // equivalent to bg-gray-800,
        "primary-content": "#e2e8f0", // equivalent to text-gray-200
        "secondary-content": "#a0aec0", // equivalent to text-gray-400
        "highlight-content": "#fbbf24", // equivalent to text-yellow-400
        accent: {
          gold: "#fbbf24", // main gold
          "gold-light": "#facc15", // light gold
          "gold-dark": "#d97706", // dark gold
        },
        // Adding error, success, warning, and info colors
        error: "#e53e3e", // red-600
        "error-darker": "#942828",
        success: "#38a169", // green-600
        warning: "#dd6b20", // orange-600
        info: "#3182ce", // blue-600

        // Optional: Adding neutral and border colors for UI consistency
        neutral: {
          light: "#f7fafc", // gray-100
          dark: "#2d3748", // gray-800
        },

        border: "#4a5568", // gray-600
      },
    },
  },
  plugins: [],
};

const config = [].reduce(
  (prev, curr) => configMerger(curr, prev),
  configMerger(inlineConfig, {
    content: {
      files: [
        "C:/repos/PeakNovelGo/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}",
        "C:/repos/PeakNovelGo/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}",
        "C:/repos/PeakNovelGo/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}",
        "C:/repos/PeakNovelGo/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}",
        "C:/repos/PeakNovelGo/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}",
        "C:/repos/PeakNovelGo/frontend/plugins/**/*.{js,ts,mjs}",
        "C:/repos/PeakNovelGo/frontend/composables/**/*.{js,ts,mjs}",
        "C:/repos/PeakNovelGo/frontend/utils/**/*.{js,ts,mjs}",
        "C:/repos/PeakNovelGo/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}",
        "C:/repos/PeakNovelGo/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}",
        "C:/repos/PeakNovelGo/frontend/app.config.{js,ts,mjs}",
      ],
    },
  })
);

module.exports = config;
