name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Install dependencies
      run: |
        cd backend
        go mod tidy
        go mod download

    - name: Create build directory
      run: mkdir -p backend/build

    - name: Run Tests
      run: |
        cd backend
        make test | go-junit-report > build/test-results.xml
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: backend/build/test-results.xml
