name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20 # Use the version you're working with

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download

    - name: Run Tests
      run: make test-all

    - name: Install JUnit reporter
      run: go install github.com/jstemmer/go-junit-report@latest
    
    - name: Convert Test Results to JUnit
      run: make test | go-junit-report > build/test-results.xml
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results.xml


